### ISSUE TITLE
Lograr la navegacion funcional de la web -Tester Auditor de calidad

### ISSUE THREAD

**Issue by EdgarHerrera2023** [SomeNinjaCoders/FinalProjectISPC#11]

**Comment by nyarlanyan** [comment]
# Rutas de la API
@app.route('/', methods=['GET'])
def pagina_principal():
    return "¡Bienvenido a la página principal de mi tienda en línea!"

# Rutas para obtener listas de objetos
@app.route('/categorias', methods=['GET'])
def obtener_categorias():
    categorias = Categoria.query.all()
    categoria_schema = CategoriaSchema(many=True)
    resultado = categoria_schema.dump(categorias)
    return jsonify(resultado), 200

@app.route('/carritos', methods=['GET'])
def obtener_carritos():
    carritos = CarritoDeCompra.query.all()
    carrito_schema = CarritoDeCompraSchema(many=True)
    resultado = carrito_schema.dump(carritos)
    return jsonify(resultado), 200

@app.route('/tiendas', methods=['GET'])
def obtener_tiendas():
    tiendas = TiendaOnline.query.all()
    tienda_schema = TiendaOnlineSchema(many=True)
    resultado = tienda_schema.dump(tiendas)
    return jsonify(resultado), 200

@app.route('/usuarios', methods=['GET'])
def obtener_usuarios():
    usuarios = Usuario.query.all()
    usuario_schema = UsuarioSchema(many=True)
    resultado = usuario_schema.dump(usuarios)
    return jsonify(resultado), 200

@app.route('/productos', methods=['GET'])
def obtener_productos():
    productos = Producto.query.all()
    producto_schema = ProductoSchema(many=True)
    resultado = producto_schema.dump(productos)
    return jsonify(resultado), 200

# Aquí deberías agregar más rutas y métodos para las otras funcionalidades que desees implementar

# ...

# Iniciar la aplicación Flask
if __name__ == '__main__':
    app.run(debug=True)
