### ISSUE TITLE
Diagrama de clases (DER)

### ISSUE THREAD

**Issue by EdgarHerrera2023** [SomeNinjaCoders/FinalProjectISPC#6]
diagramas de entidad-relación (ERD)

**Comment by nyarlanyan** [comment]
![Diagrama sin título drawio](https://github.com/SomeNinjaCoders/FinalProjectISPC/assets/101076064/afa59087-872f-44d6-819b-bfb141e2f437)

**Comment by nyarlanyan** [comment]
![Diagrama sin título drawio(1)](https://github.com/SomeNinjaCoders/FinalProjectISPC/assets/101076064/a45b4f35-fe97-4667-844c-7b25d3b0236e)

**Comment by nyarlanyan** [comment]
![Diagrama de clases drawio](https://github.com/SomeNinjaCoders/FinalProjectISPC/assets/101076064/ef03e57f-847b-48ec-abeb-11c8432863b5)
rehice el diagrama

**Comment by nyarlanyan** [comment]
![Diagrama DER](https://github.com/SomeNinjaCoders/FinalProjectISPC/assets/101076064/30c94b6e-631a-4d63-b8a8-94afe7c0e530)
